/*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import { useRef, useState } from "react";
import { Float, useGLTF, useTexture } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { easing } from "maath";

const Cube = ({ ...props }) => {
  const { nodes } = useGLTF("models/cube.glb");

  const texture = useTexture("textures/cube.png");

  const cubeRef = useRef();
  const groupRef = useRef();
  const [hovered, setHovered] = useState(false);

  // Grow the cube while hovered for a tactile, interactive feel.
  useFrame((_, delta) => {
    if (!groupRef.current) return;
    const scale = hovered ? 0.92 : 0.74;
    easing.damp3(groupRef.current.scale, [scale, scale, scale], 0.25, delta);
  });

  useGSAP(() => {
    gsap
      .timeline({
        repeat: -1,
        repeatDelay: 0.5,
      })
      .to(cubeRef.current.rotation, {
        y: hovered ? "+=2" : `+=${Math.PI * 2}`,
        x: hovered ? "+=2" : `-=${Math.PI * 2}`,
        duration: 2.5,
        stagger: {
          each: 0.15,
        },
      });
  });

  return (
    <Float floatIntensity={2}>
      <group
        ref={groupRef}
        position={[9, -4, 0]}
        rotation={[2.6, 0.8, -1.8]}
        scale={0.74}
        dispose={null}
        {...props}
      >
        <mesh
          ref={cubeRef}
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={nodes.Cube.material}
          onPointerEnter={(e) => {
            e.stopPropagation();
            setHovered(true);
            document.body.style.cursor = "pointer";
          }}
          onPointerOut={() => {
            setHovered(false);
            document.body.style.cursor = "auto";
          }}
        >
          <meshMatcapMaterial matcap={texture} toneMapped={false} />
        </mesh>
      </group>
    </Float>
  );
};

useGLTF.preload("models/cube.glb");

export default Cube;
